language: node_js
services:
  - mongodb
node_js:
  - '0.10'
deploy:
  provider: heroku
  api_key:
    secure: idbGpOvsOUnjOqhQxlpSbJYgTDQ837mY9nKZv79BCRj+h0yTYCwRHdxApUq8zRsuFjUiLyYRNF+sotm9JAjIZOLtwfR1TditAXyqaNPj+9LUWW0D9jWhGF9T5z7cg0zh3ojEW4V2DWpmV28ZuaJg3pLT6iYMOgunDX+U7lUVQT8=
  app: ainsleyperfect
  on:
    repo: MrMaksimize/loveplat2
  run:
    - restart
